spring:
    application:
        name: hlt-bmi-calc-service
    zipkin:
        base-url: http://zipkin:9411

server:
    port: 8083

eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        service-url:
            defaultZone: http://hlt-discovery-service:8761/eureka

springdoc:
    swagger-ui:
        operationsSorter: method